name: Release Private SDKs

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  generate-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout API Repo
        uses: actions/checkout@v4

      - name: Extract Version
        id: version
        run: echo "version=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT

      - name: Install Buf
        run: |
          echo "Installing Buf"
          curl -sSL https://github.com/bufbuild/buf/releases/latest/download/buf-$(uname -s)-$(uname -m) -o /usr/local/bin/buf
          chmod +x /usr/local/bin/buf

      - name: Generate SDKs
        run: |
          echo "Generating SDKs"
          buf generate

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Push Java SDK
        run: |
          echo "Pushing Java SDK"
          VERSION=${{ steps.version.outputs.version }}
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/jahjahWei/meta-api-sdk.git
          cp -r gen/meta-api-sdk/* meta-api-sdk/
          cd meta-api-sdk
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add .

          if git rev-parse --verify HEAD >/dev/null 2>&1; then
            git commit -m "Sync Java SDK v$VERSION" || echo "No changes"
          else
            git commit -m "Initial commit: Sync Java SDK v$VERSION"
          fi

          git tag v$VERSION || echo "tag exists"

          if ! git show-ref --verify --quiet refs/remotes/origin/master; then
            git push origin HEAD:master --tags
          else
            git push origin master --tags
          fi
          
          mvn clean deploy -DskipTests -s settings.xml
